
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 9;
  public static final int MENOS = 6;
  public static final int PTVIRG = 2;
  public static final int IDENT = 19;
  public static final int ABRE_PARENT = 10;
  public static final int FECHA_PARENT = 11;
  public static final int KW_IF = 17;
  public static final int PTO = 3;
  public static final int OP_RELACIONAL = 12;
  public static final int ABRE_COLCH = 15;
  public static final int FECHA_COLCH = 16;
  public static final int MAIS = 5;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int MULT = 8;
  public static final int VIRG = 4;
  public static final int DIV = 7;
  public static final int error = 1;
  public static final int ABRE_CHAVE = 13;
  public static final int FECHA_CHAVE = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTVIRG",
  "PTO",
  "VIRG",
  "MAIS",
  "MENOS",
  "DIV",
  "MULT",
  "MOD",
  "ABRE_PARENT",
  "FECHA_PARENT",
  "OP_RELACIONAL",
  "ABRE_CHAVE",
  "FECHA_CHAVE",
  "ABRE_COLCH",
  "FECHA_COLCH",
  "KW_IF",
  "NUMBER",
  "IDENT"
  };
}

