
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java.util.Scanner;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\045\000\002\015\010\000\002\002\004\000\002\007" +
    "\005\000\002\007\003\000\002\012\004\000\002\012\002" +
    "\000\002\020\002\000\002\011\007\000\002\010\005\000" +
    "\002\010\002\000\002\014\004\000\002\014\003\000\002" +
    "\013\003\000\002\013\006\000\002\013\003\000\002\021" +
    "\002\000\002\022\002\000\002\016\013\000\002\017\005" +
    "\000\002\017\003\000\002\017\003\000\002\023\002\000" +
    "\002\002\005\000\002\003\005\000\002\003\005\000\002" +
    "\003\004\000\002\003\003\000\002\004\005\000\002\004" +
    "\005\000\002\004\005\000\002\004\003\000\002\005\003" +
    "\000\002\005\005\000\002\005\003\000\002\006\006\000" +
    "\002\006\005\000\002\006\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\107\000\004\024\005\001\002\000\004\002\111\001" +
    "\002\000\004\031\006\001\002\000\006\020\ufffc\031\011" +
    "\001\002\000\004\031\103\001\002\000\004\020\016\001" +
    "\002\000\006\022\014\031\ufffe\001\002\000\006\020\ufffc" +
    "\031\011\001\002\000\004\020\ufffd\001\002\000\004\023" +
    "\015\001\002\000\004\031\uffff\001\002\000\014\010\021" +
    "\016\023\025\ufff2\030\024\031\017\001\002\000\032\004" +
    "\uffdd\005\uffdd\007\uffdd\010\uffdd\011\uffdd\012\uffdd\013\uffdd" +
    "\014\uffdd\015\uffdd\017\uffdd\022\uffdd\023\uffdd\001\002\000" +
    "\016\010\ufff3\016\ufff3\021\ufff3\025\ufff3\030\ufff3\031\ufff3" +
    "\001\002\000\010\016\023\030\024\031\017\001\002\000" +
    "\004\025\065\001\002\000\012\010\021\016\023\030\024" +
    "\031\017\001\002\000\024\004\uffe2\007\uffe2\010\uffe2\011" +
    "\uffe2\012\uffe2\013\uffe2\015\uffe2\017\uffe2\023\uffe2\001\002" +
    "\000\016\004\uffe7\007\uffe7\010\uffe7\015\uffe7\017\uffe7\023" +
    "\uffe7\001\002\000\024\004\uffe0\005\044\007\uffe0\010\uffe0" +
    "\011\uffe0\012\uffe0\013\uffe0\014\060\022\043\001\002\000" +
    "\016\010\ufff5\016\ufff5\021\ufff5\025\ufff5\030\ufff5\031\ufff5" +
    "\001\002\000\016\010\ufff6\016\ufff6\021\ufff6\025\ufff6\030" +
    "\ufff6\031\ufff6\001\002\000\024\004\uffe3\007\uffe3\010\uffe3" +
    "\011\054\012\053\013\052\015\uffe3\017\uffe3\023\uffe3\001" +
    "\002\000\010\004\uffec\007\037\010\040\001\002\000\016" +
    "\010\021\016\023\021\034\025\ufff2\030\024\031\017\001" +
    "\002\000\004\002\001\001\002\000\016\010\ufff7\016\ufff7" +
    "\021\ufff7\025\ufff7\030\ufff7\031\ufff7\001\002\000\004\004" +
    "\051\001\002\000\010\016\023\030\024\031\017\001\002" +
    "\000\010\016\023\030\024\031\017\001\002\000\030\004" +
    "\uffe0\005\044\007\uffe0\010\uffe0\011\uffe0\012\uffe0\013\uffe0" +
    "\015\uffe0\017\uffe0\022\043\023\uffe0\001\002\000\016\004" +
    "\uffe9\007\uffe9\010\uffe9\015\uffe9\017\uffe9\023\uffe9\001\002" +
    "\000\012\010\021\016\023\030\024\031\017\001\002\000" +
    "\004\031\045\001\002\000\032\004\uffde\005\uffde\007\uffde" +
    "\010\uffde\011\uffde\012\uffde\013\uffde\014\uffde\015\uffde\017" +
    "\uffde\022\uffde\023\uffde\001\002\000\010\007\037\010\040" +
    "\023\047\001\002\000\032\004\uffdf\005\uffdf\007\uffdf\010" +
    "\uffdf\011\uffdf\012\uffdf\013\uffdf\014\uffdf\015\uffdf\017\uffdf" +
    "\022\uffdf\023\uffdf\001\002\000\016\004\uffea\007\uffea\010" +
    "\uffea\015\uffea\017\uffea\023\uffea\001\002\000\016\010\uffeb" +
    "\016\uffeb\021\uffeb\025\uffeb\030\uffeb\031\uffeb\001\002\000" +
    "\010\016\023\030\024\031\017\001\002\000\010\016\023" +
    "\030\024\031\017\001\002\000\010\016\023\030\024\031" +
    "\017\001\002\000\016\004\uffe5\007\uffe5\010\uffe5\015\uffe5" +
    "\017\uffe5\023\uffe5\001\002\000\016\004\uffe6\007\uffe6\010" +
    "\uffe6\015\uffe6\017\uffe6\023\uffe6\001\002\000\016\004\uffe4" +
    "\007\uffe4\010\uffe4\015\uffe4\017\uffe4\023\uffe4\001\002\000" +
    "\012\010\021\016\023\030\024\031\017\001\002\000\010" +
    "\004\062\007\037\010\040\001\002\000\016\010\ufff4\016" +
    "\ufff4\021\ufff4\025\ufff4\030\ufff4\031\ufff4\001\002\000\010" +
    "\007\037\010\040\017\064\001\002\000\024\004\uffe1\007" +
    "\uffe1\010\uffe1\011\uffe1\012\uffe1\013\uffe1\015\uffe1\017\uffe1" +
    "\023\uffe1\001\002\000\004\016\066\001\002\000\016\010" +
    "\021\016\023\026\067\027\070\030\024\031\017\001\002" +
    "\000\004\017\uffee\001\002\000\004\017\uffed\001\002\000" +
    "\010\007\037\010\040\015\100\001\002\000\004\017\073" +
    "\001\002\000\004\020\074\001\002\000\014\010\ufff1\016" +
    "\ufff1\025\ufff1\030\ufff1\031\ufff1\001\002\000\014\010\021" +
    "\016\023\025\ufff2\030\024\031\017\001\002\000\016\010" +
    "\021\016\023\021\077\025\ufff2\030\024\031\017\001\002" +
    "\000\016\010\ufff0\016\ufff0\021\ufff0\025\ufff0\030\ufff0\031" +
    "\ufff0\001\002\000\012\010\021\016\023\030\024\031\017" +
    "\001\002\000\010\007\037\010\040\017\uffef\001\002\000" +
    "\016\004\uffe8\007\uffe8\010\uffe8\015\uffe8\017\uffe8\023\uffe8" +
    "\001\002\000\006\004\ufffb\006\ufffb\001\002\000\006\004" +
    "\ufff8\006\ufff8\001\002\000\006\004\106\006\107\001\002" +
    "\000\006\020\ufffa\031\ufffa\001\002\000\004\031\110\001" +
    "\002\000\006\004\ufff9\006\ufff9\001\002\000\004\002\000" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\107\000\004\015\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\007\006\011\011\012\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\007\006\011\011\012\012\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\024\002\026\003" +
    "\031\004\024\005\030\006\025\013\027\014\032\016\017" +
    "\021\021\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\004\101\005\030\006\040\001\001\000\002\001\001" +
    "\000\012\003\062\004\024\005\030\006\040\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\023" +
    "\035\001\001\000\022\002\026\003\031\004\024\005\030" +
    "\006\025\013\034\016\017\021\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\004\047" +
    "\005\030\006\040\001\001\000\010\004\041\005\030\006" +
    "\040\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\003\045\004\024\005\030\006\040\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\004\056\005" +
    "\030\006\040\001\001\000\010\004\055\005\030\006\040" +
    "\001\001\000\010\004\054\005\030\006\040\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\003\060\004\024\005\030\006\040\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\003\070\004\024\005\030\006" +
    "\040\017\071\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\022\074\001\001\000\024\002\026\003\031\004\024" +
    "\005\030\006\025\013\027\014\075\016\017\021\021\001" +
    "\001\000\022\002\026\003\031\004\024\005\030\006\025" +
    "\013\034\016\017\021\021\001\001\000\002\001\001\000" +
    "\012\003\100\004\024\005\030\006\040\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\020\103\001\001\000" +
    "\004\010\104\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


 
    public int contador = 0;
    public double somatorio = 0.0;
    public boolean usandoVariavel = false; 
    
    public void imprimirRelatorio() {
        System.out.println("\nForam reconhecidas e computadas:");
        System.out.println(this.contador + " expressoes");
        System.out.println("Cujo somatorio foi: " + this.somatorio);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= KW_PROGRAM IDENT varDecl_aux ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // type ::= IDENT ABRE_COLCH FECHA_COLCH 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // type ::= IDENT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // varDecl_aux ::= varDecl varDecl_aux 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_aux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // varDecl_aux ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_aux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NT$0 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 System.out.print("Declaracao variavel:" + id); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // varDecl ::= type IDENT NT$0 varDecl_op PTVIRG 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		 System.out.println(""); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // varDecl_op ::= varDecl_op VIRG IDENT 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.print(", " + id); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_op",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // varDecl_op ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_op",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // statement_aux ::= statement_aux statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement_aux",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // statement_aux ::= statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement_aux",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // statement ::= expr_ptv 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // statement ::= designator IGUAL expr PTVIRG 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Number d = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 System.out.println ("Atribuicao reconhecida: " + e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // statement ::= if_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$1 ::= 
            {
              Object RESULT =null;
 System.out.print("if("); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NT$2 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
 System.out.println("){"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // if_stmt ::= NT$1 KW_IF ABRE_PARENT condicao FECHA_PARENT ABRE_CHAVE NT$2 statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 System.out.println("}"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // condicao ::= expr OP_RELACIONAL expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e1 = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number e2 = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                boolean resultado = false;
                double val1 = e1.doubleValue();
                double val2 = e2.doubleValue();
                
                switch (op) {
                    case "<": resultado = (val1 < val2); break;
                    case "<=": resultado = (val1 <= val2); break;
                    case ">": resultado = (val1 > val2); break;
                    case ">=": resultado = (val1 >= val2); break;
                    case "==": resultado = (val1 == val2); break;
                    case "!=": resultado = (val1 != val2); break;
                    default: System.out.print("*Simbolo desconhecido*");
                }
                System.out.print(resultado);
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // condicao ::= KW_TRUE 
            {
              Object RESULT =null;
		 System.out.print("true"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // condicao ::= KW_FALSE 
            {
              Object RESULT =null;
		 System.out.print("false"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // NT$3 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 
                parser.contador++;
                parser.somatorio += e.doubleValue();
                System.out.println("  = " + e); 
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr_ptv ::= expr NT$3 PTVIRG 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_ptv",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr ::= expr MAIS term 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e.doubleValue() + t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= expr MENOS term 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e.doubleValue() - t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr ::= MENOS term 
            {
              Number RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = -t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= term 
            {
              Number RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // term ::= factor MULT term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f.doubleValue() * t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // term ::= factor DIV term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            double den = t.doubleValue();
            if (den == 0) {
                if (parser.usandoVariavel) {
                    Scanner ler = new Scanner(System.in);
                    do {
                        System.out.println("ERRO DE SEMANTICA: O denominador de variavel nao pode ser zero!");
                        System.out.print("Informe um novo valor para o denominador: ");
                        den = ler.nextDouble();
                    } while (den == 0);
                } else {
                    System.out.println("ERRO DE SEMANTICA: Divisao literal por zero! (Operacao abortada)");
                    den = 1.0; 
                }
            }
            RESULT = f.doubleValue() / den; 
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // term ::= factor MOD term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            if (f instanceof Integer && t instanceof Integer) {
                RESULT = f.intValue() % t.intValue();
            } else {
                System.out.println("ERRO DE SEMANTICA: A operacao MOD (%) so esta definida para Inteiros!");
                RESULT = 0; 
            }
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // term ::= factor 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // factor ::= NUMBER 
            {
              Number RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number n = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
             parser.usandoVariavel = false; 
             RESULT = n; 
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // factor ::= ABRE_PARENT expr FECHA_PARENT 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // factor ::= designator 
            {
              Number RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number d = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = d; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // designator ::= designator ABRE_COLCH expr FECHA_COLCH 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
                double index = e.doubleValue();
                if (index < 0) {
                    System.out.println("ERRO DE SEMANTICA: Indice do vetor nao pode ser negativo!");
                    Scanner ler = new Scanner(System.in);
                    do {
                        System.out.print("Informe um NOVO valor valido (>= 0) para o indice: ");
                        index = ler.nextDouble();
                    } while (index < 0);
                }
                parser.usandoVariavel = true;
                RESULT = Double.valueOf(1.0);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // designator ::= designator PTO IDENT 
            {
              Number RESULT =null;
		 
                parser.usandoVariavel = true;
                RESULT = Double.valueOf(1.0);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // designator ::= IDENT 
            {
              Number RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                Scanner ler = new Scanner(System.in);
                double num1;
                System.out.print("Informe o valor da variavel (" + id + "): ");
                num1 = ler.nextDouble();
                parser.usandoVariavel = true;
                if (num1 % 1 == 0) {
                    RESULT = Integer.valueOf((int)num1);
                } else {
                    RESULT = Double.valueOf(num1);
                }
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
