
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\065\000\002\015\010\000\002\002\004\000\002\007" +
    "\005\000\002\007\003\000\002\012\004\000\002\012\002" +
    "\000\002\011\006\000\002\010\005\000\002\010\002\000" +
    "\002\014\004\000\002\014\003\000\002\013\003\000\002" +
    "\013\006\000\002\013\003\000\002\013\003\000\002\013" +
    "\003\000\002\013\003\000\002\016\012\000\002\026\002" +
    "\000\002\016\011\000\002\027\002\000\002\020\007\000" +
    "\002\020\002\000\002\021\011\000\002\030\002\000\002" +
    "\022\015\000\002\023\006\000\002\023\003\000\002\024" +
    "\005\000\002\024\002\000\002\031\002\000\002\025\014" +
    "\000\002\017\005\000\002\017\003\000\002\017\003\000" +
    "\002\017\002\000\002\002\004\000\002\003\005\000\002" +
    "\003\005\000\002\003\004\000\002\003\003\000\002\032" +
    "\002\000\002\003\005\000\002\004\005\000\002\004\005" +
    "\000\002\004\005\000\002\004\003\000\002\005\003\000" +
    "\002\005\005\000\002\005\003\000\002\006\006\000\002" +
    "\006\005\000\002\006\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\171\000\004\024\005\001\002\000\004\002\173\001" +
    "\002\000\004\035\006\001\002\000\006\020\ufffc\035\011" +
    "\001\002\000\004\035\166\001\002\000\004\020\016\001" +
    "\002\000\006\022\014\035\ufffe\001\002\000\006\020\ufffc" +
    "\035\011\001\002\000\004\020\ufffd\001\002\000\004\023" +
    "\015\001\002\000\004\035\uffff\001\002\000\022\010\017" +
    "\016\022\025\025\027\035\030\uffe9\031\uffe3\034\032\035" +
    "\023\001\002\000\010\016\022\034\032\035\023\001\002" +
    "\000\024\010\ufff3\016\ufff3\021\ufff3\025\ufff3\027\ufff3\030" +
    "\ufff3\031\ufff3\034\ufff3\035\ufff3\001\002\000\024\010\ufff7" +
    "\016\ufff7\021\ufff7\025\ufff7\027\ufff7\030\ufff7\031\ufff7\034" +
    "\ufff7\035\ufff7\001\002\000\012\010\017\016\022\034\032" +
    "\035\023\001\002\000\042\004\uffcd\005\uffcd\007\uffcd\010" +
    "\uffcd\011\uffcd\012\uffcd\013\uffcd\014\uffcd\015\uffcd\016\uffcd" +
    "\017\uffcd\020\uffcd\022\uffcd\023\uffcd\034\uffcd\035\uffcd\001" +
    "\002\000\016\004\163\007\050\010\052\016\uffd8\034\uffd8" +
    "\035\uffd8\001\002\000\020\010\017\016\137\020\uffde\032" +
    "\062\033\063\034\032\035\023\001\002\000\024\010\ufff1" +
    "\016\ufff1\021\ufff1\025\ufff1\027\ufff1\030\ufff1\031\ufff1\034" +
    "\ufff1\035\ufff1\001\002\000\004\031\126\001\002\000\004" +
    "\030\104\001\002\000\024\010\ufff6\016\ufff6\021\ufff6\025" +
    "\ufff6\027\ufff6\030\ufff6\031\ufff6\034\ufff6\035\ufff6\001\002" +
    "\000\034\004\uffd2\007\uffd2\010\uffd2\011\uffd2\012\uffd2\013" +
    "\uffd2\015\uffd2\016\uffd2\017\uffd2\020\uffd2\023\uffd2\034\uffd2" +
    "\035\uffd2\001\002\000\024\010\017\016\022\021\103\025" +
    "\025\027\035\030\uffe9\031\uffe3\034\032\035\023\001\002" +
    "\000\034\004\uffd3\007\uffd3\010\uffd3\011\077\012\076\013" +
    "\075\015\uffd3\016\uffd3\017\uffd3\020\uffd3\023\uffd3\034\uffd3" +
    "\035\uffd3\001\002\000\004\016\061\001\002\000\032\004" +
    "\uffd0\005\044\007\uffd0\010\uffd0\011\uffd0\012\uffd0\013\uffd0" +
    "\014\043\016\uffd0\022\042\034\uffd0\035\uffd0\001\002\000" +
    "\026\004\uffd9\007\uffd9\010\uffd9\015\uffd9\016\uffd9\017\uffd9" +
    "\020\uffd9\023\uffd9\034\uffd9\035\uffd9\001\002\000\024\010" +
    "\ufff4\016\ufff4\021\ufff4\025\ufff4\027\ufff4\030\ufff4\031\ufff4" +
    "\034\ufff4\035\ufff4\001\002\000\024\010\ufff2\016\ufff2\021" +
    "\ufff2\025\ufff2\027\ufff2\030\ufff2\031\ufff2\034\ufff2\035\ufff2" +
    "\001\002\000\012\010\017\016\022\034\032\035\023\001" +
    "\002\000\012\010\017\016\022\034\032\035\023\001\002" +
    "\000\004\035\045\001\002\000\042\004\uffce\005\uffce\007" +
    "\uffce\010\uffce\011\uffce\012\uffce\013\uffce\014\uffce\015\uffce" +
    "\016\uffce\017\uffce\020\uffce\022\uffce\023\uffce\034\uffce\035" +
    "\uffce\001\002\000\040\004\uffd0\005\044\007\uffd0\010\uffd0" +
    "\011\uffd0\012\uffd0\013\uffd0\015\uffd0\016\uffd0\017\uffd0\020" +
    "\uffd0\022\042\023\uffd0\034\uffd0\035\uffd0\001\002\000\016" +
    "\004\051\007\050\010\052\016\uffd8\034\uffd8\035\uffd8\001" +
    "\002\000\010\016\022\034\032\035\023\001\002\000\024" +
    "\010\ufff5\016\ufff5\021\ufff5\025\ufff5\027\ufff5\030\ufff5\031" +
    "\ufff5\034\ufff5\035\ufff5\001\002\000\010\016\022\034\032" +
    "\035\023\001\002\000\010\016\022\034\032\035\023\001" +
    "\002\000\026\004\uffd7\007\uffd7\010\uffd7\015\uffd7\016\uffd7" +
    "\017\uffd7\020\uffd7\023\uffd7\034\uffd7\035\uffd7\001\002\000" +
    "\026\004\uffdb\007\uffdb\010\uffdb\015\uffdb\016\uffdb\017\uffdb" +
    "\020\uffdb\023\uffdb\034\uffdb\035\uffdb\001\002\000\026\004" +
    "\uffdc\007\uffdc\010\uffdc\015\uffdc\016\uffdc\017\uffdc\020\uffdc" +
    "\023\uffdc\034\uffdc\035\uffdc\001\002\000\016\007\050\010" +
    "\052\016\uffd8\023\060\034\uffd8\035\uffd8\001\002\000\042" +
    "\004\uffcf\005\uffcf\007\uffcf\010\uffcf\011\uffcf\012\uffcf\013" +
    "\uffcf\014\uffcf\015\uffcf\016\uffcf\017\uffcf\020\uffcf\022\uffcf" +
    "\023\uffcf\034\uffcf\035\uffcf\001\002\000\020\010\017\016" +
    "\022\017\uffde\032\062\033\063\034\032\035\023\001\002" +
    "\000\010\004\uffe0\017\uffe0\020\uffe0\001\002\000\010\004" +
    "\uffdf\017\uffdf\020\uffdf\001\002\000\016\007\050\010\052" +
    "\015\073\016\uffd8\034\uffd8\035\uffd8\001\002\000\004\017" +
    "\066\001\002\000\004\020\067\001\002\000\022\010\017" +
    "\016\022\025\025\027\035\030\uffe9\031\uffe3\034\032\035" +
    "\023\001\002\000\024\010\017\016\022\021\072\025\025" +
    "\027\035\030\uffe9\031\uffe3\034\032\035\023\001\002\000" +
    "\024\010\ufff8\016\ufff8\021\ufff8\025\ufff8\027\ufff8\030\ufff8" +
    "\031\ufff8\034\ufff8\035\ufff8\001\002\000\024\010\uffea\016" +
    "\uffea\021\uffea\025\uffea\027\uffea\030\uffea\031\uffea\034\uffea" +
    "\035\uffea\001\002\000\012\010\017\016\022\034\032\035" +
    "\023\001\002\000\022\004\uffe1\007\050\010\052\016\uffd8" +
    "\017\uffe1\020\uffe1\034\uffd8\035\uffd8\001\002\000\010\016" +
    "\022\034\032\035\023\001\002\000\010\016\022\034\032" +
    "\035\023\001\002\000\010\016\022\034\032\035\023\001" +
    "\002\000\026\004\uffd5\007\uffd5\010\uffd5\015\uffd5\016\uffd5" +
    "\017\uffd5\020\uffd5\023\uffd5\034\uffd5\035\uffd5\001\002\000" +
    "\026\004\uffd6\007\uffd6\010\uffd6\015\uffd6\016\uffd6\017\uffd6" +
    "\020\uffd6\023\uffd6\034\uffd6\035\uffd6\001\002\000\026\004" +
    "\uffd4\007\uffd4\010\uffd4\015\uffd4\016\uffd4\017\uffd4\020\uffd4" +
    "\023\uffd4\034\uffd4\035\uffd4\001\002\000\004\002\001\001" +
    "\002\000\004\016\105\001\002\000\006\004\107\035\023" +
    "\001\002\000\010\005\044\014\123\022\042\001\002\000" +
    "\020\004\uffe6\010\uffe6\016\uffe6\032\uffe6\033\uffe6\034\uffe6" +
    "\035\uffe6\001\002\000\020\004\uffde\010\017\016\022\032" +
    "\062\033\063\034\032\035\023\001\002\000\004\004\112" +
    "\001\002\000\006\017\uffe4\035\023\001\002\000\010\005" +
    "\044\014\121\022\042\001\002\000\004\017\115\001\002" +
    "\000\004\020\116\001\002\000\022\010\017\016\022\025" +
    "\025\027\035\030\uffe9\031\uffe3\034\032\035\023\001\002" +
    "\000\024\010\017\016\022\021\120\025\025\027\035\030" +
    "\uffe9\031\uffe3\034\032\035\023\001\002\000\024\010\uffe8" +
    "\016\uffe8\021\uffe8\025\uffe8\027\uffe8\030\uffe8\031\uffe8\034" +
    "\uffe8\035\uffe8\001\002\000\012\010\017\016\022\034\032" +
    "\035\023\001\002\000\016\007\050\010\052\016\uffd8\017" +
    "\uffe5\034\uffd8\035\uffd8\001\002\000\012\010\017\016\022" +
    "\034\032\035\023\001\002\000\016\004\125\007\050\010" +
    "\052\016\uffd8\034\uffd8\035\uffd8\001\002\000\020\004\uffe7" +
    "\010\uffe7\016\uffe7\032\uffe7\033\uffe7\034\uffe7\035\uffe7\001" +
    "\002\000\004\020\127\001\002\000\022\010\017\016\022" +
    "\025\025\027\035\030\uffe9\031\uffe3\034\032\035\023\001" +
    "\002\000\024\010\017\016\022\021\131\025\025\027\035" +
    "\030\uffe9\031\uffe3\034\032\035\023\001\002\000\004\027" +
    "\132\001\002\000\004\016\133\001\002\000\020\010\017" +
    "\016\022\017\uffde\032\062\033\063\034\032\035\023\001" +
    "\002\000\004\017\135\001\002\000\004\004\136\001\002" +
    "\000\024\010\uffe2\016\uffe2\021\uffe2\025\uffe2\027\uffe2\030" +
    "\uffe2\031\uffe2\034\uffe2\035\uffe2\001\002\000\020\010\017" +
    "\016\022\017\uffde\032\062\033\063\034\032\035\023\001" +
    "\002\000\004\020\uffef\001\002\000\004\020\142\001\002" +
    "\000\022\010\017\016\022\025\025\027\035\030\uffe9\031" +
    "\uffe3\034\032\035\023\001\002\000\024\010\017\016\022" +
    "\021\144\025\025\027\035\030\uffe9\031\uffe3\034\032\035" +
    "\023\001\002\000\026\010\uffeb\016\uffeb\021\uffeb\025\uffeb" +
    "\026\uffed\027\uffeb\030\uffeb\031\uffeb\034\uffeb\035\uffeb\001" +
    "\002\000\024\010\uffee\016\uffee\021\uffee\025\uffee\027\uffee" +
    "\030\uffee\031\uffee\034\uffee\035\uffee\001\002\000\004\026" +
    "\147\001\002\000\004\020\150\001\002\000\022\010\017" +
    "\016\022\025\025\027\035\030\uffe9\031\uffe3\034\032\035" +
    "\023\001\002\000\024\010\017\016\022\021\152\025\025" +
    "\027\035\030\uffe9\031\uffe3\034\032\035\023\001\002\000" +
    "\024\010\uffec\016\uffec\021\uffec\025\uffec\027\uffec\030\uffec" +
    "\031\uffec\034\uffec\035\uffec\001\002\000\020\007\050\010" +
    "\052\015\073\016\uffd8\017\162\034\uffd8\035\uffd8\001\002" +
    "\000\004\017\155\001\002\000\004\020\156\001\002\000" +
    "\022\010\017\016\022\025\025\027\035\030\uffe9\031\uffe3" +
    "\034\032\035\023\001\002\000\024\010\017\016\022\021" +
    "\160\025\025\027\035\030\uffe9\031\uffe3\034\032\035\023" +
    "\001\002\000\026\010\uffeb\016\uffeb\021\uffeb\025\uffeb\026" +
    "\uffed\027\uffeb\030\uffeb\031\uffeb\034\uffeb\035\uffeb\001\002" +
    "\000\024\010\ufff0\016\ufff0\021\ufff0\025\ufff0\027\ufff0\030" +
    "\ufff0\031\ufff0\034\ufff0\035\ufff0\001\002\000\034\004\uffd1" +
    "\007\uffd1\010\uffd1\011\uffd1\012\uffd1\013\uffd1\015\uffd1\016" +
    "\uffd1\017\uffd1\020\uffd1\023\uffd1\034\uffd1\035\uffd1\001\002" +
    "\000\024\010\uffdd\016\uffdd\021\uffdd\025\uffdd\027\uffdd\030" +
    "\uffdd\031\uffdd\034\uffdd\035\uffdd\001\002\000\016\007\050" +
    "\010\052\016\uffd8\017\162\034\uffd8\035\uffd8\001\002\000" +
    "\026\004\uffda\007\uffda\010\uffda\015\uffda\016\uffda\017\uffda" +
    "\020\uffda\023\uffda\034\uffda\035\uffda\001\002\000\006\004" +
    "\ufff9\006\ufff9\001\002\000\006\004\170\006\171\001\002" +
    "\000\006\020\ufffb\035\ufffb\001\002\000\004\035\172\001" +
    "\002\000\006\004\ufffa\006\ufffa\001\002\000\004\002\000" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\171\000\004\015\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\007\006\011\011\012\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\007\006\011\011\012\012\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\034\002\030\003" +
    "\023\004\036\005\033\006\035\013\020\014\032\016\037" +
    "\021\017\022\040\025\025\030\027\031\026\001\001\000" +
    "\010\004\164\005\033\006\045\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\003\163\004\036\005\033\006" +
    "\045\001\001\000\002\001\001\000\004\032\052\001\001" +
    "\000\014\003\063\004\036\005\033\006\045\017\137\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\032\002\030\003" +
    "\023\004\036\005\033\006\035\013\070\016\037\021\017" +
    "\022\040\025\025\030\027\031\026\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\003\056\004" +
    "\036\005\033\006\045\001\001\000\012\003\046\004\036" +
    "\005\033\006\045\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\032\052\001\001\000\010" +
    "\004\055\005\033\006\045\001\001\000\002\001\001\000" +
    "\010\004\054\005\033\006\045\001\001\000\010\004\053" +
    "\005\033\006\045\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\032\052\001\001\000\002" +
    "\001\001\000\014\003\063\004\036\005\033\006\045\017" +
    "\064\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\032\052\001\001\000\002\001\001\000\002\001\001\000" +
    "\034\002\030\003\023\004\036\005\033\006\035\013\020" +
    "\014\067\016\037\021\017\022\040\025\025\030\027\031" +
    "\026\001\001\000\032\002\030\003\023\004\036\005\033" +
    "\006\035\013\070\016\037\021\017\022\040\025\025\030" +
    "\027\031\026\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\003\073\004\036\005\033\006\045\001\001\000" +
    "\004\032\052\001\001\000\010\004\101\005\033\006\045" +
    "\001\001\000\010\004\100\005\033\006\045\001\001\000" +
    "\010\004\077\005\033\006\045\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\006\105\023\107\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\003\063\004\036\005" +
    "\033\006\045\017\110\001\001\000\002\001\001\000\006" +
    "\006\112\024\113\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\034\002\030\003\023\004\036" +
    "\005\033\006\035\013\020\014\116\016\037\021\017\022" +
    "\040\025\025\030\027\031\026\001\001\000\032\002\030" +
    "\003\023\004\036\005\033\006\035\013\070\016\037\021" +
    "\017\022\040\025\025\030\027\031\026\001\001\000\002" +
    "\001\001\000\012\003\121\004\036\005\033\006\045\001" +
    "\001\000\004\032\052\001\001\000\012\003\123\004\036" +
    "\005\033\006\045\001\001\000\004\032\052\001\001\000" +
    "\002\001\001\000\002\001\001\000\034\002\030\003\023" +
    "\004\036\005\033\006\035\013\020\014\127\016\037\021" +
    "\017\022\040\025\025\030\027\031\026\001\001\000\032" +
    "\002\030\003\023\004\036\005\033\006\035\013\070\016" +
    "\037\021\017\022\040\025\025\030\027\031\026\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\003\063\004" +
    "\036\005\033\006\045\017\133\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\003\152\004" +
    "\036\005\033\006\045\017\153\001\001\000\004\026\140" +
    "\001\001\000\002\001\001\000\034\002\030\003\023\004" +
    "\036\005\033\006\035\013\020\014\142\016\037\021\017" +
    "\022\040\025\025\030\027\031\026\001\001\000\032\002" +
    "\030\003\023\004\036\005\033\006\035\013\070\016\037" +
    "\021\017\022\040\025\025\030\027\031\026\001\001\000" +
    "\006\020\144\027\145\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\034\002\030\003\023\004" +
    "\036\005\033\006\035\013\020\014\150\016\037\021\017" +
    "\022\040\025\025\030\027\031\026\001\001\000\032\002" +
    "\030\003\023\004\036\005\033\006\035\013\070\016\037" +
    "\021\017\022\040\025\025\030\027\031\026\001\001\000" +
    "\002\001\001\000\004\032\052\001\001\000\002\001\001" +
    "\000\002\001\001\000\034\002\030\003\023\004\036\005" +
    "\033\006\035\013\020\014\156\016\037\021\017\022\040" +
    "\025\025\030\027\031\026\001\001\000\032\002\030\003" +
    "\023\004\036\005\033\006\035\013\070\016\037\021\017" +
    "\022\040\025\025\030\027\031\026\001\001\000\006\020" +
    "\160\027\145\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\032\052\001\001\000\002\001" +
    "\001\000\004\010\166\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


 
    public boolean deveExecutarBloco = false; 
    public boolean usandoVariavel = false; 
    
    public void defineErro(int linha, int coluna, String texto) {
        Scanner sc = (Scanner) this.getScanner();
        sc.defineErro(linha, coluna, texto);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= KW_PROGRAM IDENT varDecl_aux ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // type ::= IDENT ABRE_COLCH FECHA_COLCH 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // type ::= IDENT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // varDecl_aux ::= varDecl varDecl_aux 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_aux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // varDecl_aux ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_aux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // varDecl ::= type IDENT varDecl_op PTVIRG 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // varDecl_op ::= varDecl_op VIRG IDENT 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_op",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // varDecl_op ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_op",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // statement_aux ::= statement_aux statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement_aux",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // statement_aux ::= statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement_aux",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // statement ::= expr_ptv 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // statement ::= designator IGUAL expr PTVIRG 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Number d = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // statement ::= if_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // statement ::= while_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // statement ::= for_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // statement ::= do_while_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // if_stmt ::= KW_IF ABRE_PARENT condicao FECHA_PARENT ABRE_CHAVE statement_aux FECHA_CHAVE else_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // NT$0 ::= 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 parser.defineErro(cleft, cright, "IF sem parenteses"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // if_stmt ::= KW_IF condicao NT$0 ABRE_CHAVE statement_aux FECHA_CHAVE else_stmt 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // NT$1 ::= 
            {
              Object RESULT =null;
 parser.deveExecutarBloco = !parser.deveExecutarBloco; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // else_stmt ::= NT$1 KW_ELSE ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_stmt",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // else_stmt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_stmt",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // while_stmt ::= KW_WHILE ABRE_PARENT condicao FECHA_PARENT ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_stmt",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // NT$2 ::= 
            {
              Object RESULT =null;
 parser.deveExecutarBloco = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // for_stmt ::= NT$2 KW_FOR ABRE_PARENT for_init condicao PTVIRG for_step FECHA_PARENT ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-10)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_stmt",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // for_init ::= designator IGUAL expr PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_init",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // for_init ::= PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_init",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // for_step ::= designator IGUAL expr 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_step",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // for_step ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_step",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // NT$3 ::= 
            {
              Object RESULT =null;
 parser.deveExecutarBloco = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // do_while_stmt ::= NT$3 KW_DO ABRE_CHAVE statement_aux FECHA_CHAVE KW_WHILE ABRE_PARENT condicao FECHA_PARENT PTVIRG 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("do_while_stmt",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // condicao ::= expr OP_RELACIONAL expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e1 = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number e2 = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                boolean resultado = false;
                double val1 = e1.doubleValue();
                double val2 = e2.doubleValue();
                
                switch (op) {
                    case "<": resultado = (val1 < val2); break;
                    case "<=": resultado = (val1 <= val2); break;
                    case ">": resultado = (val1 > val2); break;
                    case ">=": resultado = (val1 >= val2); break;
                    case "==": resultado = (val1 == val2); break;
                    case "!=": resultado = (val1 != val2); break;
                }
                parser.deveExecutarBloco = resultado;
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condicao ::= KW_TRUE 
            {
              Object RESULT =null;
		 parser.deveExecutarBloco = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicao ::= KW_FALSE 
            {
              Object RESULT =null;
		 parser.deveExecutarBloco = false; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicao ::= 
            {
              Object RESULT =null;
		 parser.deveExecutarBloco = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr_ptv ::= expr PTVIRG 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_ptv",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= expr MAIS term 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e.doubleValue() + t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= expr MENOS term 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e.doubleValue() - t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= MENOS term 
            {
              Number RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = -t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= term 
            {
              Number RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // NT$4 ::= 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 parser.defineErro(eleft, eright, "Expressao sem operador."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$4",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= expr NT$4 term 
            {
              Number RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Number) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // term ::= factor MULT term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f.doubleValue() * t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // term ::= factor DIV term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            double den = t.doubleValue();
            if (den == 0) {
                // ROTEIRO 9: ERRO SEMÂNTICO (NOTIFICAR EM VEZ DE PEDIR)
                parser.defineErro(tleft, tright, "Divisao por zero.");
                den = 1.0; 
            }
            RESULT = f.doubleValue() / den; 
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // term ::= factor MOD term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            if (f instanceof Integer && t instanceof Integer) {
                RESULT = f.intValue() % t.intValue();
            } else {
                parser.defineErro(fleft, tright, "A operacao MOD (%) so esta definida para Inteiros!");
                RESULT = 0; 
            }
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // term ::= factor 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // factor ::= NUMBER 
            {
              Number RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number n = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // factor ::= ABRE_PARENT expr FECHA_PARENT 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // factor ::= designator 
            {
              Number RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number d = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = d; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // designator ::= designator ABRE_COLCH expr FECHA_COLCH 
            {
              Number RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Number d = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
                double index = e.doubleValue();
                if (index < 0) {
                    parser.defineErro(dleft, dright, "Indice do vetor nao pode ser negativo!");
                }
                RESULT = Double.valueOf(1.0);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // designator ::= designator PTO IDENT 
            {
              Number RESULT =null;
		 
                RESULT = Double.valueOf(1.0);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // designator ::= IDENT 
            {
              Number RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                RESULT = Double.valueOf(1.0); // Simplificado para evitar travar a execução no Roteiro 9
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
