import java_cup.runtime.*;

/* TERMINAIS */
terminal PTVIRG, MAIS, MENOS, MULT, DIV, MOD, ABRE_PARENT, FECHA_PARENT;
terminal Double NUMBER;

/* NÃO TERMINAIS */
non terminal expr_list, expr_ptv;
non terminal Double expr, term, factor;

/* REGRAS DE PRODUÇÃO */
expr_list ::= expr_list expr_ptv
            | expr_ptv;

expr_ptv ::= expr:e {: 
                System.out.println("= " + e); 
             :} PTVIRG; 

expr ::= expr:e MAIS term:t {:
            System.out.println("+ ");
            RESULT = e + t;
         :}
       | expr:e MENOS term:t {:
            System.out.println("- ");
            RESULT = e - t;
         :}
       | MENOS term:t {:
            System.out.println("u- ");
            RESULT = -t;
         :}
       | term:t {: 
            RESULT = new Double(t.doubleValue()); 
         :};

/* ATIVIDADE 3: Recursividade à Esquerda aplicada na regra 'term' */
/* ATIVIDADE 2: Operador MOD adicionado com a mesma precedência de MULT e DIV */
term ::= term:t MULT factor:f {:
            System.out.println("* ");
            RESULT = t * f;
         :}
       | term:t DIV factor:f {:
            System.out.println("/ ");
            RESULT = t / f;
         :}
       | term:t MOD factor:f {:
            System.out.println("% ");
            RESULT = t % f;
         :}
       | factor:f {: 
            RESULT = new Double(f.doubleValue()); 
         :};

factor ::= NUMBER:n {:
            System.out.print(n + " ");
            RESULT = new Double(n.doubleValue());
         :}
       | ABRE_PARENT expr:e FECHA_PARENT {:
            RESULT = new Double(e.doubleValue());
         :};
