
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FECHA_PARENT = 9;
  public static final int MAIS = 3;
  public static final int PTVIRG = 2;
  public static final int MENOS = 4;
  public static final int NUMBER = 10;
  public static final int ABRE_PARENT = 8;
  public static final int MULT = 5;
  public static final int MOD = 7;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTVIRG",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "MOD",
  "ABRE_PARENT",
  "FECHA_PARENT",
  "NUMBER"
  };
}

