
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\065\000\002\015\010\000\002\002\004\000\002\007" +
    "\005\000\002\007\003\000\002\012\004\000\002\012\002" +
    "\000\002\011\006\000\002\010\005\000\002\010\002\000" +
    "\002\014\004\000\002\014\003\000\002\013\003\000\002" +
    "\013\006\000\002\013\003\000\002\013\003\000\002\013" +
    "\003\000\002\013\003\000\002\016\012\000\002\016\004" +
    "\000\002\026\002\000\002\020\007\000\002\020\002\000" +
    "\002\021\011\000\002\021\004\000\002\027\002\000\002" +
    "\022\015\000\002\023\006\000\002\023\003\000\002\024" +
    "\005\000\002\024\002\000\002\030\002\000\002\025\014" +
    "\000\002\025\004\000\002\017\005\000\002\017\003\000" +
    "\002\017\003\000\002\017\002\000\002\017\003\000\002" +
    "\002\004\000\002\003\005\000\002\003\005\000\002\003" +
    "\004\000\002\003\003\000\002\004\005\000\002\004\005" +
    "\000\002\004\005\000\002\004\003\000\002\005\003\000" +
    "\002\005\005\000\002\005\003\000\002\006\006\000\002" +
    "\006\005\000\002\006\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\164\000\004\024\005\001\002\000\004\002\166\001" +
    "\002\000\004\035\006\001\002\000\006\020\ufffc\035\011" +
    "\001\002\000\004\035\161\001\002\000\004\020\016\001" +
    "\002\000\006\022\014\035\ufffe\001\002\000\006\020\ufffc" +
    "\035\011\001\002\000\004\020\ufffd\001\002\000\004\023" +
    "\015\001\002\000\004\035\uffff\001\002\000\022\010\017" +
    "\016\022\025\025\027\034\030\037\031\027\034\031\035" +
    "\023\001\002\000\010\016\022\034\031\035\023\001\002" +
    "\000\024\010\ufff3\016\ufff3\021\ufff3\025\ufff3\027\ufff3\030" +
    "\ufff3\031\ufff3\034\ufff3\035\ufff3\001\002\000\024\010\ufff7" +
    "\016\ufff7\021\ufff7\025\ufff7\027\ufff7\030\ufff7\031\ufff7\034" +
    "\ufff7\035\ufff7\001\002\000\012\010\017\016\022\034\031" +
    "\035\023\001\002\000\032\004\uffcd\005\uffcd\007\uffcd\010" +
    "\uffcd\011\uffcd\012\uffcd\013\uffcd\014\uffcd\015\uffcd\017\uffcd" +
    "\022\uffcd\023\uffcd\001\002\000\010\004\155\007\072\010" +
    "\073\001\002\000\006\003\140\016\141\001\002\000\024" +
    "\010\ufff1\016\ufff1\021\ufff1\025\ufff1\027\ufff1\030\ufff1\031" +
    "\ufff1\034\ufff1\035\ufff1\001\002\000\006\003\127\020\uffe3" +
    "\001\002\000\024\010\ufff6\016\ufff6\021\ufff6\025\ufff6\027" +
    "\ufff6\030\ufff6\031\ufff6\034\ufff6\035\ufff6\001\002\000\024" +
    "\004\uffd2\007\uffd2\010\uffd2\011\uffd2\012\uffd2\013\uffd2\015" +
    "\uffd2\017\uffd2\023\uffd2\001\002\000\024\010\017\016\022" +
    "\021\125\025\025\027\034\030\037\031\027\034\031\035" +
    "\023\001\002\000\024\004\uffd3\007\uffd3\010\uffd3\011\121" +
    "\012\120\013\117\015\uffd3\017\uffd3\023\uffd3\001\002\000" +
    "\006\003\110\016\111\001\002\000\024\004\uffd0\005\067" +
    "\007\uffd0\010\uffd0\011\uffd0\012\uffd0\013\uffd0\014\105\022" +
    "\065\001\002\000\016\004\uffd7\007\uffd7\010\uffd7\015\uffd7" +
    "\017\uffd7\023\uffd7\001\002\000\004\016\uffe9\001\002\000" +
    "\024\010\ufff4\016\ufff4\021\ufff4\025\ufff4\027\ufff4\030\ufff4" +
    "\031\ufff4\034\ufff4\035\ufff4\001\002\000\024\010\ufff2\016" +
    "\ufff2\021\ufff2\025\ufff2\027\ufff2\030\ufff2\031\ufff2\034\ufff2" +
    "\035\ufff2\001\002\000\004\016\043\001\002\000\006\004" +
    "\045\035\023\001\002\000\010\005\067\014\102\022\065" +
    "\001\002\000\022\003\uffe6\004\uffe6\010\uffe6\016\uffe6\032" +
    "\uffe6\033\uffe6\034\uffe6\035\uffe6\001\002\000\022\003\052" +
    "\004\uffdd\010\017\016\022\032\050\033\051\034\031\035" +
    "\023\001\002\000\030\004\uffd0\005\067\007\uffd0\010\uffd0" +
    "\011\uffd0\012\uffd0\013\uffd0\015\uffd0\017\uffd0\022\065\023" +
    "\uffd0\001\002\000\006\004\uffdf\017\uffdf\001\002\000\006" +
    "\004\uffde\017\uffde\001\002\000\006\004\uffdc\017\uffdc\001" +
    "\002\000\010\007\072\010\073\015\100\001\002\000\004" +
    "\004\055\001\002\000\006\017\uffe4\035\023\001\002\000" +
    "\010\005\067\014\066\022\065\001\002\000\004\017\060" +
    "\001\002\000\004\020\061\001\002\000\022\010\017\016" +
    "\022\025\025\027\034\030\037\031\027\034\031\035\023" +
    "\001\002\000\024\010\017\016\022\021\064\025\025\027" +
    "\034\030\037\031\027\034\031\035\023\001\002\000\024" +
    "\010\ufff8\016\ufff8\021\ufff8\025\ufff8\027\ufff8\030\ufff8\031" +
    "\ufff8\034\ufff8\035\ufff8\001\002\000\024\010\uffe8\016\uffe8" +
    "\021\uffe8\025\uffe8\027\uffe8\030\uffe8\031\uffe8\034\uffe8\035" +
    "\uffe8\001\002\000\012\010\017\016\022\034\031\035\023" +
    "\001\002\000\012\010\017\016\022\034\031\035\023\001" +
    "\002\000\004\035\070\001\002\000\032\004\uffce\005\uffce" +
    "\007\uffce\010\uffce\011\uffce\012\uffce\013\uffce\014\uffce\015" +
    "\uffce\017\uffce\022\uffce\023\uffce\001\002\000\010\007\072" +
    "\010\073\017\uffe5\001\002\000\010\016\022\034\031\035" +
    "\023\001\002\000\010\016\022\034\031\035\023\001\002" +
    "\000\016\004\uffd9\007\uffd9\010\uffd9\015\uffd9\017\uffd9\023" +
    "\uffd9\001\002\000\016\004\uffda\007\uffda\010\uffda\015\uffda" +
    "\017\uffda\023\uffda\001\002\000\010\007\072\010\073\023" +
    "\077\001\002\000\032\004\uffcf\005\uffcf\007\uffcf\010\uffcf" +
    "\011\uffcf\012\uffcf\013\uffcf\014\uffcf\015\uffcf\017\uffcf\022" +
    "\uffcf\023\uffcf\001\002\000\012\010\017\016\022\034\031" +
    "\035\023\001\002\000\012\004\uffe0\007\072\010\073\017" +
    "\uffe0\001\002\000\012\010\017\016\022\034\031\035\023" +
    "\001\002\000\010\004\104\007\072\010\073\001\002\000" +
    "\022\003\uffe7\004\uffe7\010\uffe7\016\uffe7\032\uffe7\033\uffe7" +
    "\034\uffe7\035\uffe7\001\002\000\012\010\017\016\022\034" +
    "\031\035\023\001\002\000\010\004\107\007\072\010\073" +
    "\001\002\000\024\010\ufff5\016\ufff5\021\ufff5\025\ufff5\027" +
    "\ufff5\030\ufff5\031\ufff5\034\ufff5\035\ufff5\001\002\000\024" +
    "\010\uffea\016\uffea\021\uffea\025\uffea\027\uffea\030\uffea\031" +
    "\uffea\034\uffea\035\uffea\001\002\000\022\003\052\010\017" +
    "\016\022\017\uffdd\032\050\033\051\034\031\035\023\001" +
    "\002\000\004\017\113\001\002\000\004\020\114\001\002" +
    "\000\022\010\017\016\022\025\025\027\034\030\037\031" +
    "\027\034\031\035\023\001\002\000\024\010\017\016\022" +
    "\021\116\025\025\027\034\030\037\031\027\034\031\035" +
    "\023\001\002\000\024\010\uffeb\016\uffeb\021\uffeb\025\uffeb" +
    "\027\uffeb\030\uffeb\031\uffeb\034\uffeb\035\uffeb\001\002\000" +
    "\010\016\022\034\031\035\023\001\002\000\010\016\022" +
    "\034\031\035\023\001\002\000\010\016\022\034\031\035" +
    "\023\001\002\000\016\004\uffd5\007\uffd5\010\uffd5\015\uffd5" +
    "\017\uffd5\023\uffd5\001\002\000\016\004\uffd6\007\uffd6\010" +
    "\uffd6\015\uffd6\017\uffd6\023\uffd6\001\002\000\016\004\uffd4" +
    "\007\uffd4\010\uffd4\015\uffd4\017\uffd4\023\uffd4\001\002\000" +
    "\004\002\001\001\002\000\004\020\130\001\002\000\024" +
    "\010\uffe1\016\uffe1\021\uffe1\025\uffe1\027\uffe1\030\uffe1\031" +
    "\uffe1\034\uffe1\035\uffe1\001\002\000\022\010\017\016\022" +
    "\025\025\027\034\030\037\031\027\034\031\035\023\001" +
    "\002\000\024\010\017\016\022\021\132\025\025\027\034" +
    "\030\037\031\027\034\031\035\023\001\002\000\004\027" +
    "\133\001\002\000\004\016\134\001\002\000\022\003\052" +
    "\010\017\016\022\017\uffdd\032\050\033\051\034\031\035" +
    "\023\001\002\000\004\017\136\001\002\000\004\004\137" +
    "\001\002\000\024\010\uffe2\016\uffe2\021\uffe2\025\uffe2\027" +
    "\uffe2\030\uffe2\031\uffe2\034\uffe2\035\uffe2\001\002\000\024" +
    "\010\uffef\016\uffef\021\uffef\025\uffef\027\uffef\030\uffef\031" +
    "\uffef\034\uffef\035\uffef\001\002\000\022\003\052\010\017" +
    "\016\022\017\uffdd\032\050\033\051\034\031\035\023\001" +
    "\002\000\004\017\143\001\002\000\004\020\144\001\002" +
    "\000\022\010\017\016\022\025\025\027\034\030\037\031" +
    "\027\034\031\035\023\001\002\000\024\010\017\016\022" +
    "\021\146\025\025\027\034\030\037\031\027\034\031\035" +
    "\023\001\002\000\026\010\uffec\016\uffec\021\uffec\025\uffec" +
    "\026\150\027\uffec\030\uffec\031\uffec\034\uffec\035\uffec\001" +
    "\002\000\024\010\ufff0\016\ufff0\021\ufff0\025\ufff0\027\ufff0" +
    "\030\ufff0\031\ufff0\034\ufff0\035\ufff0\001\002\000\004\020" +
    "\uffee\001\002\000\004\020\152\001\002\000\022\010\017" +
    "\016\022\025\025\027\034\030\037\031\027\034\031\035" +
    "\023\001\002\000\024\010\017\016\022\021\154\025\025" +
    "\027\034\030\037\031\027\034\031\035\023\001\002\000" +
    "\024\010\uffed\016\uffed\021\uffed\025\uffed\027\uffed\030\uffed" +
    "\031\uffed\034\uffed\035\uffed\001\002\000\024\010\uffdb\016" +
    "\uffdb\021\uffdb\025\uffdb\027\uffdb\030\uffdb\031\uffdb\034\uffdb" +
    "\035\uffdb\001\002\000\010\007\072\010\073\017\157\001" +
    "\002\000\024\004\uffd1\007\uffd1\010\uffd1\011\uffd1\012\uffd1" +
    "\013\uffd1\015\uffd1\017\uffd1\023\uffd1\001\002\000\016\004" +
    "\uffd8\007\uffd8\010\uffd8\015\uffd8\017\uffd8\023\uffd8\001\002" +
    "\000\006\004\ufff9\006\ufff9\001\002\000\006\004\163\006" +
    "\164\001\002\000\006\020\ufffb\035\ufffb\001\002\000\004" +
    "\035\165\001\002\000\006\004\ufffa\006\ufffa\001\002\000" +
    "\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\164\000\004\015\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\007\006\011\011\012\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\007\006\011\011\012\012\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\030\002\027\003" +
    "\023\004\035\005\032\006\034\013\020\014\031\016\037" +
    "\021\017\022\040\025\025\001\001\000\010\004\157\005" +
    "\032\006\046\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\003\155\004\035\005\032\006\046\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\030\125\001\001\000\002\001\001\000" +
    "\002\001\001\000\026\002\027\003\023\004\035\005\032" +
    "\006\034\013\062\016\037\021\017\022\040\025\025\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\027\041\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\006\043" +
    "\023\045\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\003\052\004\035\005\032\006\046\017\053\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\006\055\024\056\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\030\002\027\003\023\004\035" +
    "\005\032\006\034\013\020\014\061\016\037\021\017\022" +
    "\040\025\025\001\001\000\026\002\027\003\023\004\035" +
    "\005\032\006\034\013\062\016\037\021\017\022\040\025" +
    "\025\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\003\075\004\035\005\032\006\046\001\001\000\012\003" +
    "\070\004\035\005\032\006\046\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\004\074\005" +
    "\032\006\046\001\001\000\010\004\073\005\032\006\046" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\003\100\004\035\005\032" +
    "\006\046\001\001\000\002\001\001\000\012\003\102\004" +
    "\035\005\032\006\046\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\003\105\004\035\005\032\006\046\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\003\052\004\035\005\032\006\046\017\111\001" +
    "\001\000\002\001\001\000\002\001\001\000\030\002\027" +
    "\003\023\004\035\005\032\006\034\013\020\014\114\016" +
    "\037\021\017\022\040\025\025\001\001\000\026\002\027" +
    "\003\023\004\035\005\032\006\034\013\062\016\037\021" +
    "\017\022\040\025\025\001\001\000\002\001\001\000\010" +
    "\004\123\005\032\006\046\001\001\000\010\004\122\005" +
    "\032\006\046\001\001\000\010\004\121\005\032\006\046" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\030\002\027\003\023\004\035\005\032\006\034\013" +
    "\020\014\130\016\037\021\017\022\040\025\025\001\001" +
    "\000\026\002\027\003\023\004\035\005\032\006\034\013" +
    "\062\016\037\021\017\022\040\025\025\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\003\052\004\035\005" +
    "\032\006\046\017\134\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\003" +
    "\052\004\035\005\032\006\046\017\141\001\001\000\002" +
    "\001\001\000\002\001\001\000\030\002\027\003\023\004" +
    "\035\005\032\006\034\013\020\014\144\016\037\021\017" +
    "\022\040\025\025\001\001\000\026\002\027\003\023\004" +
    "\035\005\032\006\034\013\062\016\037\021\017\022\040" +
    "\025\025\001\001\000\004\020\146\001\001\000\002\001" +
    "\001\000\004\026\150\001\001\000\002\001\001\000\030" +
    "\002\027\003\023\004\035\005\032\006\034\013\020\014" +
    "\152\016\037\021\017\022\040\025\025\001\001\000\026" +
    "\002\027\003\023\004\035\005\032\006\034\013\062\016" +
    "\037\021\017\022\040\025\025\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\161\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


 
    public boolean deveExecutarBloco = false; 
    public boolean usandoVariavel = false; 
    public int contador = 0;
    public double somatorio = 0.0;
    
    public void imprimirRelatorio() {
        System.out.println("\nForam reconhecidas e computadas:");
        System.out.println(this.contador + " expressoes");
        System.out.println("Cujo somatorio foi: " + this.somatorio);
    }
    
    // Tratamento de erro Roteiro 10
    public void syntax_error(Symbol s) {
        this.defineErro(s.left, s.right);
    }
    
    public void defineErro(int linha, int coluna) {
        Scanner lexer = (Scanner) this.getScanner();
        lexer.getListaErros().defineErro(linha, coluna);
    }
    
    public void defineErro(int linha, int coluna, String texto) {
        Scanner lexer = (Scanner) this.getScanner();
        lexer.getListaErros().defineErro(linha, coluna, texto);
    }
    
    public void defineErro(String texto) {
        Scanner lexer = (Scanner) this.getScanner();
        lexer.getListaErros().defineErro(texto);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= KW_PROGRAM IDENT varDecl_aux ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // type ::= IDENT ABRE_COLCH FECHA_COLCH 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // type ::= IDENT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // varDecl_aux ::= varDecl varDecl_aux 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_aux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // varDecl_aux ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_aux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // varDecl ::= type IDENT varDecl_op PTVIRG 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // varDecl_op ::= varDecl_op VIRG IDENT 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_op",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // varDecl_op ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_op",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // statement_aux ::= statement_aux statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement_aux",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // statement_aux ::= statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement_aux",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // statement ::= expr_ptv 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // statement ::= designator IGUAL expr PTVIRG 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Number d = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // statement ::= if_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // statement ::= while_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // statement ::= for_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // statement ::= do_while_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // if_stmt ::= KW_IF ABRE_PARENT condicao FECHA_PARENT ABRE_CHAVE statement_aux FECHA_CHAVE else_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // if_stmt ::= KW_IF error 
            {
              Object RESULT =null;
		 parser.defineErro("IF incompleto ou com erro de sintaxe"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // NT$0 ::= 
            {
              Object RESULT =null;
 parser.deveExecutarBloco = !parser.deveExecutarBloco; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // else_stmt ::= KW_ELSE NT$0 ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_stmt",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // else_stmt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_stmt",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // while_stmt ::= KW_WHILE ABRE_PARENT condicao FECHA_PARENT ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_stmt",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // while_stmt ::= KW_WHILE error 
            {
              Object RESULT =null;
		 parser.defineErro("WHILE incompleto ou com erro de sintaxe"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_stmt",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // NT$1 ::= 
            {
              Object RESULT =null;
 parser.deveExecutarBloco = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // for_stmt ::= KW_FOR NT$1 ABRE_PARENT for_init condicao PTVIRG for_step FECHA_PARENT ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_stmt",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // for_init ::= designator IGUAL expr PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_init",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // for_init ::= PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_init",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // for_step ::= designator IGUAL expr 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_step",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // for_step ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_step",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // NT$2 ::= 
            {
              Object RESULT =null;
 parser.deveExecutarBloco = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // do_while_stmt ::= KW_DO NT$2 ABRE_CHAVE statement_aux FECHA_CHAVE KW_WHILE ABRE_PARENT condicao FECHA_PARENT PTVIRG 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("do_while_stmt",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // do_while_stmt ::= KW_DO error 
            {
              Object RESULT =null;
		 parser.defineErro("DO-WHILE incompleto ou com erro de sintaxe"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("do_while_stmt",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condicao ::= expr OP_RELACIONAL expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e1 = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number e2 = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                boolean resultado = false;
                double val1 = e1.doubleValue();
                double val2 = e2.doubleValue();
                switch (op) {
                    case "<": resultado = (val1 < val2); break;
                    case "<=": resultado = (val1 <= val2); break;
                    case ">": resultado = (val1 > val2); break;
                    case ">=": resultado = (val1 >= val2); break;
                    case "==": resultado = (val1 == val2); break;
                    case "!=": resultado = (val1 != val2); break;
                }
                parser.deveExecutarBloco = resultado;
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicao ::= KW_TRUE 
            {
              Object RESULT =null;
		 parser.deveExecutarBloco = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicao ::= KW_FALSE 
            {
              Object RESULT =null;
		 parser.deveExecutarBloco = false; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condicao ::= 
            {
              Object RESULT =null;
		 parser.deveExecutarBloco = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // condicao ::= error 
            {
              Object RESULT =null;
		 parser.defineErro("Condicao com erro (faltou operador relacional)"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr_ptv ::= expr PTVIRG 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_ptv",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= expr MAIS term 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e.doubleValue() + t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= expr MENOS term 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e.doubleValue() - t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= MENOS term 
            {
              Number RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = -t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= term 
            {
              Number RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // term ::= factor MULT term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f.doubleValue() * t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // term ::= factor DIV term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            double den = t.doubleValue();
            if (den == 0) {
                parser.defineErro(tleft, tright, "Divisao por zero.");
                den = 1.0; 
            }
            RESULT = f.doubleValue() / den; 
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // term ::= factor MOD term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            if (f instanceof Integer && t instanceof Integer) {
                RESULT = f.intValue() % t.intValue();
            } else {
                parser.defineErro(fleft, tright, "A operacao MOD (%) so esta definida para Inteiros!");
                RESULT = 0; 
            }
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // term ::= factor 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // factor ::= NUMBER 
            {
              Number RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number n = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
             parser.usandoVariavel = false; 
             RESULT = n; 
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // factor ::= ABRE_PARENT expr FECHA_PARENT 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // factor ::= designator 
            {
              Number RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number d = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = d; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // designator ::= designator ABRE_COLCH expr FECHA_COLCH 
            {
              Number RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Number d = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
                double index = e.doubleValue();
                if (index < 0) {
                    parser.defineErro(dleft, dright, "Indice do vetor nao pode ser negativo!");
                }
                parser.usandoVariavel = true;
                RESULT = Double.valueOf(1.0);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // designator ::= designator PTO IDENT 
            {
              Number RESULT =null;
		 
                parser.usandoVariavel = true;
                RESULT = Double.valueOf(1.0);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // designator ::= IDENT 
            {
              Number RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                parser.usandoVariavel = true;
                RESULT = Double.valueOf(1.0); 
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
