
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java.util.Scanner;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\071\000\002\015\010\000\002\002\004\000\002\007" +
    "\005\000\002\007\003\000\002\012\004\000\002\012\002" +
    "\000\002\011\006\000\002\010\005\000\002\010\002\000" +
    "\002\014\004\000\002\014\003\000\002\013\003\000\002" +
    "\013\006\000\002\013\003\000\002\013\003\000\002\013" +
    "\003\000\002\013\003\000\002\026\002\000\002\027\002" +
    "\000\002\030\002\000\002\016\015\000\002\031\002\000" +
    "\002\020\007\000\002\020\002\000\002\032\002\000\002" +
    "\033\002\000\002\021\013\000\002\034\002\000\002\035" +
    "\002\000\002\022\016\000\002\023\006\000\002\023\003" +
    "\000\002\024\005\000\002\024\002\000\002\036\002\000" +
    "\002\037\002\000\002\025\015\000\002\017\005\000\002" +
    "\017\003\000\002\017\003\000\002\017\002\000\002\040" +
    "\002\000\002\002\005\000\002\003\005\000\002\003\005" +
    "\000\002\003\004\000\002\003\003\000\002\004\005\000" +
    "\002\004\005\000\002\004\005\000\002\004\003\000\002" +
    "\005\003\000\002\005\005\000\002\005\003\000\002\006" +
    "\006\000\002\006\005\000\002\006\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\170\000\004\024\005\001\002\000\004\002\172\001" +
    "\002\000\004\035\006\001\002\000\006\020\ufffc\035\011" +
    "\001\002\000\004\035\165\001\002\000\004\020\016\001" +
    "\002\000\006\022\014\035\ufffe\001\002\000\006\020\ufffc" +
    "\035\011\001\002\000\004\020\ufffd\001\002\000\004\023" +
    "\015\001\002\000\004\035\uffff\001\002\000\022\010\017" +
    "\016\022\025\ufff0\027\uffe9\030\uffe6\031\uffdf\034\033\035" +
    "\023\001\002\000\010\016\022\034\033\035\023\001\002" +
    "\000\024\010\ufff3\016\ufff3\021\ufff3\025\ufff3\027\ufff3\030" +
    "\ufff3\031\ufff3\034\ufff3\035\ufff3\001\002\000\024\010\ufff7" +
    "\016\ufff7\021\ufff7\025\ufff7\027\ufff7\030\ufff7\031\ufff7\034" +
    "\ufff7\035\ufff7\001\002\000\012\010\017\016\022\034\033" +
    "\035\023\001\002\000\032\004\uffc9\005\uffc9\007\uffc9\010" +
    "\uffc9\011\uffc9\012\uffc9\013\uffc9\014\uffc9\015\uffc9\017\uffc9" +
    "\022\uffc9\023\uffc9\001\002\000\010\004\uffd8\007\050\010" +
    "\052\001\002\000\004\031\146\001\002\000\004\030\123" +
    "\001\002\000\024\010\ufff1\016\ufff1\021\ufff1\025\ufff1\027" +
    "\ufff1\030\ufff1\031\ufff1\034\ufff1\035\ufff1\001\002\000\004" +
    "\027\113\001\002\000\004\025\067\001\002\000\024\010" +
    "\ufff6\016\ufff6\021\ufff6\025\ufff6\027\ufff6\030\ufff6\031\ufff6" +
    "\034\ufff6\035\ufff6\001\002\000\024\004\uffce\007\uffce\010" +
    "\uffce\011\uffce\012\uffce\013\uffce\015\uffce\017\uffce\023\uffce" +
    "\001\002\000\024\010\017\016\022\021\066\025\ufff0\027" +
    "\uffe9\030\uffe6\031\uffdf\034\033\035\023\001\002\000\024" +
    "\004\uffcf\007\uffcf\010\uffcf\011\061\012\060\013\057\015" +
    "\uffcf\017\uffcf\023\uffcf\001\002\000\024\004\uffcc\005\044" +
    "\007\uffcc\010\uffcc\011\uffcc\012\uffcc\013\uffcc\014\043\022" +
    "\042\001\002\000\016\004\uffd3\007\uffd3\010\uffd3\015\uffd3" +
    "\017\uffd3\023\uffd3\001\002\000\024\010\ufff4\016\ufff4\021" +
    "\ufff4\025\ufff4\027\ufff4\030\ufff4\031\ufff4\034\ufff4\035\ufff4" +
    "\001\002\000\024\010\ufff2\016\ufff2\021\ufff2\025\ufff2\027" +
    "\ufff2\030\ufff2\031\ufff2\034\ufff2\035\ufff2\001\002\000\012" +
    "\010\017\016\022\034\033\035\023\001\002\000\012\010" +
    "\017\016\022\034\033\035\023\001\002\000\004\035\045" +
    "\001\002\000\032\004\uffca\005\uffca\007\uffca\010\uffca\011" +
    "\uffca\012\uffca\013\uffca\014\uffca\015\uffca\017\uffca\022\uffca" +
    "\023\uffca\001\002\000\030\004\uffcc\005\044\007\uffcc\010" +
    "\uffcc\011\uffcc\012\uffcc\013\uffcc\015\uffcc\017\uffcc\022\042" +
    "\023\uffcc\001\002\000\010\004\051\007\050\010\052\001" +
    "\002\000\010\016\022\034\033\035\023\001\002\000\024" +
    "\010\ufff5\016\ufff5\021\ufff5\025\ufff5\027\ufff5\030\ufff5\031" +
    "\ufff5\034\ufff5\035\ufff5\001\002\000\010\016\022\034\033" +
    "\035\023\001\002\000\016\004\uffd5\007\uffd5\010\uffd5\015" +
    "\uffd5\017\uffd5\023\uffd5\001\002\000\016\004\uffd6\007\uffd6" +
    "\010\uffd6\015\uffd6\017\uffd6\023\uffd6\001\002\000\010\007" +
    "\050\010\052\023\056\001\002\000\032\004\uffcb\005\uffcb" +
    "\007\uffcb\010\uffcb\011\uffcb\012\uffcb\013\uffcb\014\uffcb\015" +
    "\uffcb\017\uffcb\022\uffcb\023\uffcb\001\002\000\010\016\022" +
    "\034\033\035\023\001\002\000\010\016\022\034\033\035" +
    "\023\001\002\000\010\016\022\034\033\035\023\001\002" +
    "\000\016\004\uffd1\007\uffd1\010\uffd1\015\uffd1\017\uffd1\023" +
    "\uffd1\001\002\000\016\004\uffd2\007\uffd2\010\uffd2\015\uffd2" +
    "\017\uffd2\023\uffd2\001\002\000\016\004\uffd0\007\uffd0\010" +
    "\uffd0\015\uffd0\017\uffd0\023\uffd0\001\002\000\024\010\ufff8" +
    "\016\ufff8\021\ufff8\025\ufff8\027\ufff8\030\ufff8\031\ufff8\034" +
    "\ufff8\035\ufff8\001\002\000\004\002\001\001\002\000\004" +
    "\016\070\001\002\000\020\010\017\016\022\017\uffd9\032" +
    "\071\033\072\034\033\035\023\001\002\000\006\004\uffdb" +
    "\017\uffdb\001\002\000\006\004\uffda\017\uffda\001\002\000" +
    "\010\007\050\010\052\015\111\001\002\000\004\017\075" +
    "\001\002\000\004\020\076\001\002\000\022\010\uffef\016" +
    "\uffef\025\uffef\027\uffef\030\uffef\031\uffef\034\uffef\035\uffef" +
    "\001\002\000\022\010\017\016\022\025\ufff0\027\uffe9\030" +
    "\uffe6\031\uffdf\034\033\035\023\001\002\000\024\010\017" +
    "\016\022\021\101\025\ufff0\027\uffe9\030\uffe6\031\uffdf\034" +
    "\033\035\023\001\002\000\026\010\uffee\016\uffee\021\uffee" +
    "\025\uffee\026\uffee\027\uffee\030\uffee\031\uffee\034\uffee\035" +
    "\uffee\001\002\000\026\010\uffea\016\uffea\021\uffea\025\uffea" +
    "\026\uffec\027\uffea\030\uffea\031\uffea\034\uffea\035\uffea\001" +
    "\002\000\004\026\105\001\002\000\024\010\uffed\016\uffed" +
    "\021\uffed\025\uffed\027\uffed\030\uffed\031\uffed\034\uffed\035" +
    "\uffed\001\002\000\004\020\106\001\002\000\022\010\017" +
    "\016\022\025\ufff0\027\uffe9\030\uffe6\031\uffdf\034\033\035" +
    "\023\001\002\000\024\010\017\016\022\021\110\025\ufff0" +
    "\027\uffe9\030\uffe6\031\uffdf\034\033\035\023\001\002\000" +
    "\024\010\uffeb\016\uffeb\021\uffeb\025\uffeb\027\uffeb\030\uffeb" +
    "\031\uffeb\034\uffeb\035\uffeb\001\002\000\012\010\017\016" +
    "\022\034\033\035\023\001\002\000\012\004\uffdc\007\050" +
    "\010\052\017\uffdc\001\002\000\004\016\114\001\002\000" +
    "\020\010\017\016\022\017\uffd9\032\071\033\072\034\033" +
    "\035\023\001\002\000\004\017\116\001\002\000\004\020" +
    "\117\001\002\000\022\010\uffe8\016\uffe8\025\uffe8\027\uffe8" +
    "\030\uffe8\031\uffe8\034\uffe8\035\uffe8\001\002\000\022\010" +
    "\017\016\022\025\ufff0\027\uffe9\030\uffe6\031\uffdf\034\033" +
    "\035\023\001\002\000\024\010\017\016\022\021\122\025" +
    "\ufff0\027\uffe9\030\uffe6\031\uffdf\034\033\035\023\001\002" +
    "\000\024\010\uffe7\016\uffe7\021\uffe7\025\uffe7\027\uffe7\030" +
    "\uffe7\031\uffe7\034\uffe7\035\uffe7\001\002\000\004\016\124" +
    "\001\002\000\006\004\126\035\023\001\002\000\010\005" +
    "\044\014\143\022\042\001\002\000\020\004\uffe2\010\uffe2" +
    "\016\uffe2\032\uffe2\033\uffe2\034\uffe2\035\uffe2\001\002\000" +
    "\020\004\uffd9\010\017\016\022\032\071\033\072\034\033" +
    "\035\023\001\002\000\004\004\131\001\002\000\006\017" +
    "\uffe0\035\023\001\002\000\010\005\044\014\141\022\042" +
    "\001\002\000\004\017\134\001\002\000\004\020\135\001" +
    "\002\000\022\010\uffe5\016\uffe5\025\uffe5\027\uffe5\030\uffe5" +
    "\031\uffe5\034\uffe5\035\uffe5\001\002\000\022\010\017\016" +
    "\022\025\ufff0\027\uffe9\030\uffe6\031\uffdf\034\033\035\023" +
    "\001\002\000\024\010\017\016\022\021\140\025\ufff0\027" +
    "\uffe9\030\uffe6\031\uffdf\034\033\035\023\001\002\000\024" +
    "\010\uffe4\016\uffe4\021\uffe4\025\uffe4\027\uffe4\030\uffe4\031" +
    "\uffe4\034\uffe4\035\uffe4\001\002\000\012\010\017\016\022" +
    "\034\033\035\023\001\002\000\010\007\050\010\052\017" +
    "\uffe1\001\002\000\012\010\017\016\022\034\033\035\023" +
    "\001\002\000\010\004\145\007\050\010\052\001\002\000" +
    "\020\004\uffe3\010\uffe3\016\uffe3\032\uffe3\033\uffe3\034\uffe3" +
    "\035\uffe3\001\002\000\004\020\147\001\002\000\022\010" +
    "\017\016\022\025\ufff0\027\uffe9\030\uffe6\031\uffdf\034\033" +
    "\035\023\001\002\000\024\010\017\016\022\021\151\025" +
    "\ufff0\027\uffe9\030\uffe6\031\uffdf\034\033\035\023\001\002" +
    "\000\004\027\152\001\002\000\004\016\153\001\002\000" +
    "\020\010\uffde\016\uffde\017\uffde\032\uffde\033\uffde\034\uffde" +
    "\035\uffde\001\002\000\020\010\017\016\022\017\uffd9\032" +
    "\071\033\072\034\033\035\023\001\002\000\004\017\156" +
    "\001\002\000\004\004\157\001\002\000\024\010\uffdd\016" +
    "\uffdd\021\uffdd\025\uffdd\027\uffdd\030\uffdd\031\uffdd\034\uffdd" +
    "\035\uffdd\001\002\000\004\004\161\001\002\000\024\010" +
    "\uffd7\016\uffd7\021\uffd7\025\uffd7\027\uffd7\030\uffd7\031\uffd7" +
    "\034\uffd7\035\uffd7\001\002\000\010\007\050\010\052\017" +
    "\163\001\002\000\024\004\uffcd\007\uffcd\010\uffcd\011\uffcd" +
    "\012\uffcd\013\uffcd\015\uffcd\017\uffcd\023\uffcd\001\002\000" +
    "\016\004\uffd4\007\uffd4\010\uffd4\015\uffd4\017\uffd4\023\uffd4" +
    "\001\002\000\006\004\ufff9\006\ufff9\001\002\000\006\004" +
    "\167\006\170\001\002\000\006\020\ufffb\035\ufffb\001\002" +
    "\000\004\035\171\001\002\000\006\004\ufffa\006\ufffa\001" +
    "\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\170\000\004\015\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\007\006\011\011\012\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\007\006\011\011\012\012\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\040\002\031\003" +
    "\023\004\036\005\034\006\035\013\020\014\033\016\037" +
    "\021\017\022\040\025\026\026\030\032\027\034\025\036" +
    "\024\001\001\000\010\004\163\005\034\006\045\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\003\161\004" +
    "\036\005\034\006\045\001\001\000\002\001\001\000\004" +
    "\040\157\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\036\002\031\003\023\004" +
    "\036\005\034\006\035\013\064\016\037\021\017\022\040" +
    "\025\026\026\030\032\027\034\025\036\024\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\003\054\004\036\005" +
    "\034\006\045\001\001\000\012\003\046\004\036\005\034" +
    "\006\045\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\004\053\005\034" +
    "\006\045\001\001\000\002\001\001\000\010\004\052\005" +
    "\034\006\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\004\063\005" +
    "\034\006\045\001\001\000\010\004\062\005\034\006\045" +
    "\001\001\000\010\004\061\005\034\006\045\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\003" +
    "\072\004\036\005\034\006\045\017\073\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\027\076\001\001\000\040" +
    "\002\031\003\023\004\036\005\034\006\035\013\020\014" +
    "\077\016\037\021\017\022\040\025\026\026\030\032\027" +
    "\034\025\036\024\001\001\000\036\002\031\003\023\004" +
    "\036\005\034\006\035\013\064\016\037\021\017\022\040" +
    "\025\026\026\030\032\027\034\025\036\024\001\001\000" +
    "\004\030\101\001\001\000\006\020\103\031\102\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\040\002\031\003\023\004\036\005\034\006\035\013\020" +
    "\014\106\016\037\021\017\022\040\025\026\026\030\032" +
    "\027\034\025\036\024\001\001\000\036\002\031\003\023" +
    "\004\036\005\034\006\035\013\064\016\037\021\017\022" +
    "\040\025\026\026\030\032\027\034\025\036\024\001\001" +
    "\000\002\001\001\000\012\003\111\004\036\005\034\006" +
    "\045\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\003\072\004\036\005\034\006\045\017\114\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\033\117\001\001" +
    "\000\040\002\031\003\023\004\036\005\034\006\035\013" +
    "\020\014\120\016\037\021\017\022\040\025\026\026\030" +
    "\032\027\034\025\036\024\001\001\000\036\002\031\003" +
    "\023\004\036\005\034\006\035\013\064\016\037\021\017" +
    "\022\040\025\026\026\030\032\027\034\025\036\024\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\006\124" +
    "\023\126\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\003\072\004\036\005\034\006\045\017\127\001\001" +
    "\000\002\001\001\000\006\006\131\024\132\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\035\135\001\001\000\040\002\031\003\023\004\036\005" +
    "\034\006\035\013\020\014\136\016\037\021\017\022\040" +
    "\025\026\026\030\032\027\034\025\036\024\001\001\000" +
    "\036\002\031\003\023\004\036\005\034\006\035\013\064" +
    "\016\037\021\017\022\040\025\026\026\030\032\027\034" +
    "\025\036\024\001\001\000\002\001\001\000\012\003\141" +
    "\004\036\005\034\006\045\001\001\000\002\001\001\000" +
    "\012\003\143\004\036\005\034\006\045\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\040\002" +
    "\031\003\023\004\036\005\034\006\035\013\020\014\147" +
    "\016\037\021\017\022\040\025\026\026\030\032\027\034" +
    "\025\036\024\001\001\000\036\002\031\003\023\004\036" +
    "\005\034\006\035\013\064\016\037\021\017\022\040\025" +
    "\026\026\030\032\027\034\025\036\024\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\037\153\001\001\000" +
    "\014\003\072\004\036\005\034\006\045\017\154\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\165\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


 
    public boolean deveExecutarBloco = false; 
    public boolean usandoVariavel = false; 


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= KW_PROGRAM IDENT varDecl_aux ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // type ::= IDENT ABRE_COLCH FECHA_COLCH 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // type ::= IDENT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // varDecl_aux ::= varDecl varDecl_aux 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_aux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // varDecl_aux ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_aux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // varDecl ::= type IDENT varDecl_op PTVIRG 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // varDecl_op ::= varDecl_op VIRG IDENT 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_op",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // varDecl_op ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("varDecl_op",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // statement_aux ::= statement_aux statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement_aux",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // statement_aux ::= statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement_aux",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // statement ::= expr_ptv 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // statement ::= designator IGUAL expr PTVIRG 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Number d = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // statement ::= if_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // statement ::= while_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // statement ::= for_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // statement ::= do_while_stmt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // NT$0 ::= 
            {
              Object RESULT =null;
 System.out.print("if("); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // NT$1 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
 System.out.println("){"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // NT$2 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
 System.out.println("}"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // if_stmt ::= NT$0 KW_IF ABRE_PARENT condicao FECHA_PARENT ABRE_CHAVE NT$1 statement_aux FECHA_CHAVE NT$2 else_stmt 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // NT$3 ::= 
            {
              Object RESULT =null;
 
                parser.deveExecutarBloco = !parser.deveExecutarBloco;
                System.out.println("else{");
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // else_stmt ::= NT$3 KW_ELSE ABRE_CHAVE statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		 System.out.println("}"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_stmt",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // else_stmt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_stmt",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // NT$4 ::= 
            {
              Object RESULT =null;
 System.out.print("while("); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$4",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // NT$5 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
 System.out.println("){"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$5",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // while_stmt ::= NT$4 KW_WHILE ABRE_PARENT condicao FECHA_PARENT ABRE_CHAVE NT$5 statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 System.out.println("}"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_stmt",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // NT$6 ::= 
            {
              Object RESULT =null;
 System.out.print("for("); parser.deveExecutarBloco = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$6",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // NT$7 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
 System.out.println("){"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$7",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // for_stmt ::= NT$6 KW_FOR ABRE_PARENT for_init condicao PTVIRG for_step FECHA_PARENT ABRE_CHAVE NT$7 statement_aux FECHA_CHAVE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 System.out.println("}"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_stmt",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // for_init ::= designator IGUAL expr PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_init",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // for_init ::= PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_init",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // for_step ::= designator IGUAL expr 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_step",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // for_step ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_step",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // NT$8 ::= 
            {
              Object RESULT =null;
 parser.deveExecutarBloco = true; System.out.println("do{"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$8",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // NT$9 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
 System.out.print("}while("); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$9",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // do_while_stmt ::= NT$8 KW_DO ABRE_CHAVE statement_aux FECHA_CHAVE KW_WHILE ABRE_PARENT NT$9 condicao FECHA_PARENT PTVIRG 
            {
              Object RESULT =null;
              // propagate RESULT from NT$9
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		 System.out.println(");"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("do_while_stmt",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // condicao ::= expr OP_RELACIONAL expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e1 = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number e2 = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                boolean resultado = false;
                double val1 = e1.doubleValue();
                double val2 = e2.doubleValue();
                
                switch (op) {
                    case "<": resultado = (val1 < val2); break;
                    case "<=": resultado = (val1 <= val2); break;
                    case ">": resultado = (val1 > val2); break;
                    case ">=": resultado = (val1 >= val2); break;
                    case "==": resultado = (val1 == val2); break;
                    case "!=": resultado = (val1 != val2); break;
                }
                parser.deveExecutarBloco = resultado;
                System.out.print(resultado);
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // condicao ::= KW_TRUE 
            {
              Object RESULT =null;
		 
                parser.deveExecutarBloco = true;
                System.out.print("true"); 
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condicao ::= KW_FALSE 
            {
              Object RESULT =null;
		 
                parser.deveExecutarBloco = false;
                System.out.print("false"); 
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // condicao ::= 
            {
              Object RESULT =null;
		 parser.deveExecutarBloco = true; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // NT$10 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 
                if (parser.deveExecutarBloco) {
                    System.out.println("  = " + e); 
                }
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$10",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr_ptv ::= expr NT$10 PTVIRG 
            {
              Object RESULT =null;
              // propagate RESULT from NT$10
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_ptv",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= expr MAIS term 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e.doubleValue() + t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= expr MENOS term 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e.doubleValue() - t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= MENOS term 
            {
              Number RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = -t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= term 
            {
              Number RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // term ::= factor MULT term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f.doubleValue() * t.doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // term ::= factor DIV term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            double den = t.doubleValue();
            if (den == 0 && parser.deveExecutarBloco) {
                if (parser.usandoVariavel) {
                    Scanner ler = new Scanner(System.in);
                    do {
                        System.out.println("ERRO DE SEMANTICA: O denominador nao pode ser zero!");
                        System.out.print("Informe um novo valor para o denominador: ");
                        den = ler.nextDouble();
                    } while (den == 0);
                } else {
                    den = 1.0; 
                }
            }
            if (den == 0) den = 1.0; 
            RESULT = f.doubleValue() / den; 
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // term ::= factor MOD term 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number t = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            if (f instanceof Integer && t instanceof Integer) {
                RESULT = f.intValue() % t.intValue();
            } else {
                RESULT = 0; 
            }
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // term ::= factor 
            {
              Number RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number f = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // factor ::= NUMBER 
            {
              Number RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number n = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
             parser.usandoVariavel = false; 
             RESULT = n; 
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // factor ::= ABRE_PARENT expr FECHA_PARENT 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // factor ::= designator 
            {
              Number RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number d = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = d; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // designator ::= designator ABRE_COLCH expr FECHA_COLCH 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Number e = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
                parser.usandoVariavel = true;
                RESULT = Double.valueOf(1.0);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // designator ::= designator PTO IDENT 
            {
              Number RESULT =null;
		 
                parser.usandoVariavel = true;
                RESULT = Double.valueOf(1.0);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // designator ::= IDENT 
            {
              Number RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                parser.usandoVariavel = true;
                RESULT = Double.valueOf(1.0); 
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("designator",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
